'use strict';
/**
 * MotoKE — a QR encoder, because the alternative at a car bazaar is reading a URL out loud.
 *
 * On a Sunday at Jamhuri there are a thousand brokers in a field. Typing each one's name
 * and number yourself is about sixty seconds a man. Holding up a phone with a code on it
 * and letting them scan is about five, and they end up on their OWN handset, which is
 * where the account has to live anyway.
 *
 * WHY THIS IS WRITTEN OUT RATHER THAN INSTALLED. This project has no dependencies and the
 * audit fails the build if one appears. A QR encoder is a well-specified algorithm with a
 * fixed answer, so writing it is a known quantity rather than a risk — and a broken QR is
 * obvious the first time somebody points a camera at it.
 *
 * SCOPE, deliberately narrow: byte mode, error level M, versions 1 to 6. That covers 106
 * characters, which is every URL this will ever hold. Stopping at 6 also stops before
 * version 7, where the format gains an extra version-information block — a whole extra
 * piece of machinery for capacity nobody here needs.
 *
 * Error level M recovers about 15% of a damaged code. That is the right level for a phone
 * screen in sunlight with a thumbprint on it.
 */

/* ------------------------------------------------------------------ */
/* GF(256) — the arithmetic Reed-Solomon is built on                   */
/* ------------------------------------------------------------------ */

/* The field is generated by 0x11D, which is what the QR specification names. */
const EXP = new Uint8Array(512);
const LOG = new Uint8Array(256);
(function buildTables() {
  let x = 1;
  for (let i = 0; i < 255; i++) {
    EXP[i] = x;
    LOG[x] = i;
    x <<= 1;
    if (x & 0x100) x ^= 0x11d;
  }
  for (let i = 255; i < 512; i++) EXP[i] = EXP[i - 255];
})();

const gfMul = (a, b) => (a === 0 || b === 0 ? 0 : EXP[LOG[a] + LOG[b]]);

/** The generator polynomial for `degree` error-correction codewords. */
function generatorPoly(degree) {
  let poly = [1];
  for (let d = 0; d < degree; d++) {
    const next = new Array(poly.length + 1).fill(0);
    for (let i = 0; i < poly.length; i++) {
      next[i] ^= gfMul(poly[i], EXP[d]);
      next[i + 1] ^= poly[i];
    }
    poly = next;
  }
  return poly;
}

/** Polynomial long division; the remainder IS the error correction. */
function ecCodewords(data, count) {
  const gen = generatorPoly(count);
  const rem = new Array(count).fill(0);
  for (const byte of data) {
    const factor = byte ^ rem[0];
    rem.shift();
    rem.push(0);
    for (let i = 0; i < count; i++) rem[i] ^= gfMul(gen[i + 1], factor);
  }
  return rem;
}

/* ------------------------------------------------------------------ */
/* the tables                                                          */
/* ------------------------------------------------------------------ */

/* Per version at error level M: [ecPerBlock, [ [blocks, dataCodewordsEach], ... ] ].
   Copied from the specification's block table rather than derived, because deriving them
   is guesswork and a wrong split produces a code that scans as nonsense rather than one
   that visibly fails. */
const VERSIONS = {
  1: { ec: 10, groups: [[1, 16]] },
  2: { ec: 16, groups: [[1, 28]] },
  3: { ec: 26, groups: [[1, 44]] },
  4: { ec: 18, groups: [[2, 32]] },
  5: { ec: 24, groups: [[2, 43]] },
  6: { ec: 16, groups: [[4, 27]] },
};

/* Where the alignment patterns sit. Version 1 has none. */
const ALIGN = { 1: [], 2: [6, 18], 3: [6, 22], 4: [6, 26], 5: [6, 30], 6: [6, 34] };

const size = (version) => version * 4 + 17;
const dataCapacity = (version) =>
  VERSIONS[version].groups.reduce((n, [blocks, each]) => n + blocks * each, 0);

/** The smallest version that holds this many bytes. */
function pickVersion(byteLength) {
  for (let v = 1; v <= 6; v++) {
    /* 4 bits of mode + 8 bits of character count = 12 bits of overhead, plus a
       4-bit terminator, so the usable payload is two codewords short of the data area. */
    if (byteLength + 2 <= dataCapacity(v)) return v;
  }
  throw new Error('Too long for a version 6 QR code: ' + byteLength + ' bytes (max ' + (dataCapacity(6) - 2) + ')');
}

/* ------------------------------------------------------------------ */
/* the bitstream                                                       */
/* ------------------------------------------------------------------ */

function encodeData(bytes, version) {
  const bits = [];
  const push = (value, length) => {
    for (let i = length - 1; i >= 0; i--) bits.push((value >> i) & 1);
  };

  push(0b0100, 4);              // byte mode
  push(bytes.length, 8);        // versions 1-9 count the characters in 8 bits
  for (const b of bytes) push(b, 8);

  const capacityBits = dataCapacity(version) * 8;
  push(0, Math.min(4, capacityBits - bits.length));   // terminator
  while (bits.length % 8) bits.push(0);               // pad to a whole codeword

  const codewords = [];
  for (let i = 0; i < bits.length; i += 8) {
    let byte = 0;
    for (let j = 0; j < 8; j++) byte = (byte << 1) | bits[i + j];
    codewords.push(byte);
  }
  /* The two alternating pad bytes the specification names. */
  const PAD = [0xec, 0x11];
  let p = 0;
  while (codewords.length < dataCapacity(version)) codewords.push(PAD[p++ % 2]);
  return codewords;
}

/**
 * Split into blocks, correct each, then INTERLEAVE.
 *
 * The interleaving is the point of the exercise: it spreads each block's bytes across the
 * whole symbol, so a thumb over one corner damages a little of every block rather than
 * destroying one of them completely.
 */
function buildCodewords(bytes, version) {
  const { ec, groups } = VERSIONS[version];
  const data = encodeData(bytes, version);

  const blocks = [];
  let at = 0;
  for (const [count, each] of groups) {
    for (let i = 0; i < count; i++) {
      const slice = data.slice(at, at + each);
      at += each;
      blocks.push({ data: slice, ec: ecCodewords(slice, ec) });
    }
  }

  const out = [];
  const longest = Math.max(...blocks.map((b) => b.data.length));
  for (let i = 0; i < longest; i++) {
    for (const b of blocks) if (i < b.data.length) out.push(b.data[i]);
  }
  for (let i = 0; i < ec; i++) {
    for (const b of blocks) out.push(b.ec[i]);
  }
  return out;
}

/* ------------------------------------------------------------------ */
/* the matrix                                                          */
/* ------------------------------------------------------------------ */

function blankMatrix(version) {
  const n = size(version);
  return {
    n,
    /* null means "nothing placed here yet", which is different from a placed white module
       and is what keeps the data placement from writing over the patterns. */
    cells: Array.from({ length: n }, () => new Array(n).fill(null)),
  };
}

function placeFinder(m, row, col) {
  for (let r = -1; r <= 7; r++) {
    for (let c = -1; c <= 7; c++) {
      const rr = row + r;
      const cc = col + c;
      if (rr < 0 || cc < 0 || rr >= m.n || cc >= m.n) continue;
      const onRing = (r >= 0 && r <= 6 && (c === 0 || c === 6))
        || (c >= 0 && c <= 6 && (r === 0 || r === 6));
      const inCore = r >= 2 && r <= 4 && c >= 2 && c <= 4;
      m.cells[rr][cc] = onRing || inCore ? 1 : 0;
    }
  }
}

function placeAlignment(m, version) {
  const centres = ALIGN[version];
  for (const r of centres) {
    for (const c of centres) {
      /* Never on top of a finder pattern. */
      if ((r <= 8 && c <= 8) || (r <= 8 && c >= m.n - 9) || (r >= m.n - 9 && c <= 8)) continue;
      for (let dr = -2; dr <= 2; dr++) {
        for (let dc = -2; dc <= 2; dc++) {
          const ring = Math.max(Math.abs(dr), Math.abs(dc));
          m.cells[r + dr][c + dc] = ring === 1 ? 0 : 1;
        }
      }
    }
  }
}

function placePatterns(m, version) {
  placeFinder(m, 0, 0);
  placeFinder(m, 0, m.n - 7);
  placeFinder(m, m.n - 7, 0);
  placeAlignment(m, version);

  // Timing: alternating modules along row 6 and column 6.
  for (let i = 8; i < m.n - 8; i++) {
    const on = i % 2 === 0 ? 1 : 0;
    if (m.cells[6][i] === null) m.cells[6][i] = on;
    if (m.cells[i][6] === null) m.cells[i][6] = on;
  }

  // The dark module. Always there, always black, always in that one place.
  m.cells[m.n - 8][8] = 1;

  // Reserve the format areas so data placement skips them.
  for (let i = 0; i < 9; i++) {
    if (m.cells[8][i] === null) m.cells[8][i] = 0;
    if (m.cells[i][8] === null) m.cells[i][8] = 0;
  }
  for (let i = 0; i < 8; i++) {
    if (m.cells[8][m.n - 1 - i] === null) m.cells[8][m.n - 1 - i] = 0;
    if (m.cells[m.n - 1 - i][8] === null) m.cells[m.n - 1 - i][8] = 0;
  }
}

/** Which cells the data may use: everything still null after the patterns are down. */
function freeCells(version) {
  const probe = blankMatrix(version);
  placePatterns(probe, version);
  return probe.cells.map((row) => row.map((v) => v === null));
}

/**
 * Lay the bits in, bottom-right upwards, two columns at a time, snaking.
 *
 * Column 6 is skipped entirely — it is the vertical timing pattern, and forgetting that
 * shifts every subsequent bit by one, which produces a perfectly valid-looking code that
 * decodes to rubbish.
 */
function placeData(m, codewords, free) {
  const bits = [];
  for (const cw of codewords) for (let i = 7; i >= 0; i--) bits.push((cw >> i) & 1);

  let bit = 0;
  let upward = true;
  for (let right = m.n - 1; right > 0; right -= 2) {
    if (right === 6) right--;
    for (let step = 0; step < m.n; step++) {
      const row = upward ? m.n - 1 - step : step;
      for (const col of [right, right - 1]) {
        if (!free[row][col]) continue;
        m.cells[row][col] = bit < bits.length ? bits[bit] : 0;
        bit++;
      }
    }
    upward = !upward;
  }
}

const MASKS = [
  (r, c) => (r + c) % 2 === 0,
  (r) => r % 2 === 0,
  (r, c) => c % 3 === 0,
  (r, c) => (r + c) % 3 === 0,
  (r, c) => (Math.floor(r / 2) + Math.floor(c / 3)) % 2 === 0,
  (r, c) => ((r * c) % 2) + ((r * c) % 3) === 0,
  (r, c) => (((r * c) % 2) + ((r * c) % 3)) % 2 === 0,
  (r, c) => (((r + c) % 2) + ((r * c) % 3)) % 2 === 0,
];

/* Format information: 5 bits (error level + mask) expanded to 15 by a BCH code, then
   XORed with a fixed pattern so an all-zero format cannot happen by accident. */
function formatBits(maskIndex) {
  const LEVEL_M = 0b00;
  let value = (LEVEL_M << 3) | maskIndex;
  let rem = value << 10;
  for (let i = 4; i >= 0; i--) {
    if (rem & (1 << (i + 10))) rem ^= 0b10100110111 << i;
  }
  return ((value << 10) | rem) ^ 0b101010000010010;
}

function placeFormat(m, maskIndex) {
  const bits = formatBits(maskIndex);
  const bit = (i) => (bits >> i) & 1;

  for (let i = 0; i <= 5; i++) m.cells[8][i] = bit(14 - i);
  m.cells[8][7] = bit(8);
  m.cells[8][8] = bit(7);
  m.cells[7][8] = bit(6);
  for (let i = 9; i <= 14; i++) m.cells[14 - i][8] = bit(14 - i);

  for (let i = 0; i <= 7; i++) m.cells[m.n - 1 - i][8] = bit(i);
  for (let i = 8; i <= 14; i++) m.cells[8][m.n - 15 + i] = bit(i);
  m.cells[m.n - 8][8] = 1;   // the dark module survives everything
}

/**
 * How bad a masked symbol looks to a scanner. Lower is better.
 *
 * All four rules from the specification. Skipping any of them is tempting and produces
 * codes that work on a good phone in good light and fail on a cheap one at a bazaar,
 * which is the only place this will ever be used.
 */
function penalty(cells, n) {
  let score = 0;

  // 1: runs of five or more of the same colour.
  for (let i = 0; i < n; i++) {
    for (const line of [cells[i], cells.map((r) => r[i])]) {
      let run = 1;
      for (let j = 1; j < n; j++) {
        if (line[j] === line[j - 1]) {
          run++;
          if (run === 5) score += 3;
          else if (run > 5) score += 1;
        } else run = 1;
      }
    }
  }

  // 2: every 2x2 block of one colour.
  for (let r = 0; r < n - 1; r++) {
    for (let c = 0; c < n - 1; c++) {
      const v = cells[r][c];
      if (v === cells[r][c + 1] && v === cells[r + 1][c] && v === cells[r + 1][c + 1]) score += 3;
    }
  }

  // 3: the finder-like sequence, which a scanner can mistake for a finder pattern.
  const PATTERN = [1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0];
  const REVERSED = [0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1];
  const matches = (line, at, pat) => pat.every((v, k) => line[at + k] === v);
  for (let i = 0; i < n; i++) {
    for (const line of [cells[i], cells.map((r) => r[i])]) {
      for (let j = 0; j + 11 <= n; j++) {
        if (matches(line, j, PATTERN) || matches(line, j, REVERSED)) score += 40;
      }
    }
  }

  // 4: how far the whole symbol is from half dark.
  let dark = 0;
  for (let r = 0; r < n; r++) for (let c = 0; c < n; c++) if (cells[r][c]) dark++;
  const pct = (dark * 100) / (n * n);
  score += Math.floor(Math.abs(pct - 50) / 5) * 10;

  return score;
}

/**
 * Encode text into a matrix of 1s and 0s.
 *
 * Returns { version, n, cells } where cells[row][col] is 1 for a dark module.
 */
function encode(text) {
  const bytes = Array.from(Buffer.from(String(text), 'utf8'));
  const version = pickVersion(bytes.length);
  const codewords = buildCodewords(bytes, version);
  const free = freeCells(version);

  let best = null;
  for (let mask = 0; mask < 8; mask++) {
    const m = blankMatrix(version);
    placePatterns(m, version);
    placeData(m, codewords, free);
    for (let r = 0; r < m.n; r++) {
      for (let c = 0; c < m.n; c++) {
        if (free[r][c] && MASKS[mask](r, c)) m.cells[r][c] ^= 1;
      }
    }
    placeFormat(m, mask);
    const score = penalty(m.cells, m.n);
    if (!best || score < best.score) best = { score, mask, cells: m.cells, n: m.n };
  }

  return { version, n: best.n, cells: best.cells, mask: best.mask };
}

/**
 * The same thing as an SVG.
 *
 * Drawn as one path of rectangles rather than a rect per module: a version 6 code is 41x41,
 * so that is up to 1,681 elements, and the path is a fraction of the bytes and renders in
 * one go. The quiet zone is four modules because anything less and scanners on cheap phones
 * start missing it — the margin is part of the specification, not padding.
 */
function svg(text, opts = {}) {
  const { n, cells, version } = encode(text);
  const quiet = opts.quiet != null ? opts.quiet : 4;
  const total = n + quiet * 2;
  const dark = opts.dark || '#000000';
  const light = opts.light || '#ffffff';

  let path = '';
  for (let r = 0; r < n; r++) {
    for (let c = 0; c < n; c++) {
      if (cells[r][c]) path += `M${c + quiet} ${r + quiet}h1v1h-1z`;
    }
  }

  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${total} ${total}" `
    + `shape-rendering="crispEdges" role="img" aria-label="QR code" data-qr-version="${version}">`
    + `<rect width="${total}" height="${total}" fill="${light}"/>`
    + `<path d="${path}" fill="${dark}"/>`
    + '</svg>';
}

module.exports = { encode, svg, pickVersion, dataCapacity, MAX_BYTES: dataCapacity(6) - 2 };
